package com.clubz.util;

/**
 * Created by mindiii on 2/22/18.
 */

public class Image_Codes_class {
    public static final String image_codes ="[\n" +
            "  {\"ad\":R.mipmap.ad}\n" +
            "  ,{\"ae\":R.mipmap.ae}\n" +
            "  ,{\"af\":R.mipmap.af}\n" +
            "  ,{\"ag\":R.mipmap.ag}\n" +
            "  ,{\"ai\":R.mipmap.ai}\n" +
            "  ,{\"al\":R.mipmap.al}\n" +
            "  ,{\"am\":R.mipmap.am}\n" +
            "  ,{\"ao\":R.mipmap.ao}\n" +
            "  ,{\"aq\":R.mipmap.aq}\n" +
            "  ,{\"ar\":R.mipmap.ar}\n" +
            "  ,{\"as\":R.mipmap.as}\n" +
            "  ,{\"at\":R.mipmap.at}\n" +
            "  ,{\"au\":R.mipmap.au}\n" +
            "  ,{\"aw\":R.mipmap.aw}\n" +
            "  ,{\"ax\":R.mipmap.ax}\n" +
            "  ,{\"az\":R.mipmap.az}\n" +
            "  ,{\"ba\":R.mipmap.ba}\n" +
            "  ,{\"bb\":R.mipmap.bb}\n" +
            "  ,{\"bd\":R.mipmap.bd}\n" +
            "  ,{\"be\":R.mipmap.be}\n" +
            "  ,{\"bf\":R.mipmap.bf}\n" +
            "  ,{\"bg\":R.mipmap.bg}\n" +
            "  ,{\"bh\":R.mipmap.bh}\n" +
            "  ,{\"bi\":R.mipmap.bi}\n" +
            "  ,{\"bj\":R.mipmap.bj}\n" +
            "  ,{\"bl\":R.mipmap.bl}\n" +
            "  ,{\"bm\":R.mipmap.bm}\n" +
            "  ,{\"bn\":R.mipmap.bn}\n" +
            "  ,{\"bo\":R.mipmap.bo}\n" +
            "  ,{\"bq\":R.mipmap.bq}\n" +
            "  ,{\"br\":R.mipmap.br}\n" +
            "  ,{\"bs\":R.mipmap.bs}\n" +
            "  ,{\"bt\":R.mipmap.bt}\n" +
            "  ,{\"bv\":R.mipmap.bv}\n" +
            "  ,{\"bw\":R.mipmap.bw}\n" +
            "  ,{\"by\":R.mipmap.by}\n" +
            "  ,{\"bz\":R.mipmap.bz}\n" +
            "  ,{\"ca\":R.mipmap.ca}\n" +
            "  ,{\"cc\":R.mipmap.cc}\n" +
            "  ,{\"cd\":R.mipmap.cd}\n" +
            "  ,{\"cf\":R.mipmap.cf}\n" +
            "  ,{\"cg\":R.mipmap.cg}\n" +
            "  ,{\"ch\":R.mipmap.ch}\n" +
            "  ,{\"ci\":R.mipmap.ci}\n" +
            "  ,{\"ck\":R.mipmap.ck}\n" +
            "  ,{\"cl\":R.mipmap.cl}\n" +
            "  ,{\"cm\":R.mipmap.cm}\n" +
            "  ,{\"cn\":R.mipmap.cn}\n" +
            "  ,{\"co\":R.mipmap.co}\n" +
            "  ,{\"cr\":R.mipmap.cr}\n" +
            "  ,{\"cu\":R.mipmap.cu}\n" +
            "  ,{\"cv\":R.mipmap.cv}\n" +
            "  ,{\"cw\":R.mipmap.cw}\n" +
            "  ,{\"cx\":R.mipmap.cx}\n" +
            "  ,{\"cy\":R.mipmap.cy}\n" +
            "  ,{\"cz\":R.mipmap.cz}\n" +
            "  ,{\"de\":R.mipmap.de}\n" +
            "  ,{\"dj\":R.mipmap.dj}\n" +
            "  ,{\"dk\":R.mipmap.dk}\n" +
            "  ,{\"dm\":R.mipmap.dm}\n" +
            "  ,{\"do\":R.mipmap.do_}\n" +
            "  ,{\"dz\":R.mipmap.dz}\n" +
            "  ,{\"ec\":R.mipmap.ec}\n" +
            "  ,{\"ee\":R.mipmap.ee}\n" +
            "  ,{\"eg\":R.mipmap.eg}\n" +
            "  ,{\"eh\":R.mipmap.eh}\n" +
            "  ,{\"er\":R.mipmap.er}\n" +
            "  ,{\"es\":R.mipmap.es}\n" +
            "  ,{\"et\":R.mipmap.et}\n" +
            "  ,{\"fi\":R.mipmap.fi}\n" +
            "  ,{\"fj\":R.mipmap.fj}\n" +
            "  ,{\"fk\":R.mipmap.fk}\n" +
            "  ,{\"fm\":R.mipmap.fm}\n" +
            "  ,{\"fo\":R.mipmap.fo}\n" +
            "  ,{\"fr\":R.mipmap.fr}\n" +
            "  ,{\"ga\":R.mipmap.ga}\n" +
            "  ,{\"gb_e\":R.mipmap.gb_engng}\n" +
            "  ,{\"gb_n\":R.mipmap.gb_nirir}\n" +
            "  ,{\"gb\":R.mipmap.gb}\n" +
            "  ,{\"gb_s\"R.mipmap.gb_sctct}\n" +
            "  ,{\"gb_w\"R.mipmap.gb_wlsls}\n" +
            "  ,{\"gd\":R.mipmap.gd}\n" +
            "  ,{\"ge\":R.mipmap.ge}\n" +
            "  ,{\"gf\":R.mipmap.gf}\n" +
            "  ,{\"gg\":R.mipmap.gg}\n" +
            "  ,{\"gh\":R.mipmap.gh}\n" +
            "  ,{\"gi\":R.mipmap.gi}\n" +
            "  ,{\"gl\":R.mipmap.gl}\n" +
            "  ,{\"gm\":R.mipmap.gm}\n" +
            "  ,{\"gn\":R.mipmap.gn}\n" +
            "  ,{\"gp\":R.mipmap.gp}\n" +
            "  ,{\"gq\":R.mipmap.gq}\n" +
            "  ,{\"gr\":R.mipmap.gr}\n" +
            "  ,{\"gs\":R.mipmap.gs}\n" +
            "  ,{\"gt\":R.mipmap.gt}\n" +
            "  ,{\"gu\":R.mipmap.gu}\n" +
            "  ,{\"gw\":R.mipmap.gw}\n" +
            "  ,{\"gy\":R.mipmap.gy}\n" +
            "  ,{\"hk\":R.mipmap.hk}\n" +
            "  ,{\"hm\":R.mipmap.hm}\n" +
            "  ,{\"hn\":R.mipmap.hn}\n" +
            "  ,{\"hr\":R.mipmap.hr}\n" +
            "  ,{\"ht\":R.mipmap.ht}\n" +
            "  ,{\"hu\":R.mipmap.hu}\n" +
            "\n" +
            "  ,{\"id\":R.mipmap.id}\n" +
            "  ,{\"ie\":R.mipmap.ie}\n" +
            "  ,{\"il\":R.mipmap.il}\n" +
            "  ,{\"im\":R.mipmap.im}\n" +
            "  ,{\"in_\":R.mipmap.in_}\n" +
            "  ,{\"io\":R.mipmap.io}\n" +
            "  ,{\"iq\":R.mipmap.iq}\n" +
            "  ,{\"ir\":R.mipmap.ir}\n" +
            "  ,{\"is\":R.mipmap.is}\n" +
            "  ,{\"it\":R.mipmap.it}\n" +
            "  ,{\"je\":R.mipmap.je}\n" +
            "  ,{\"jm\":R.mipmap.jm}\n" +
            "  ,{\"jo\":R.mipmap.jo}\n" +
            "  ,{\"jp\":R.mipmap.jp}\n" +
            "  ,{\"ke\":R.mipmap.ke}\n" +
            "  ,{\"kg\":R.mipmap.kg}\n" +
            "  ,{\"kh\":R.mipmap.kh}\n" +
            "  ,{\"ki\":R.mipmap.ki}\n" +
            "  ,{\"km\":R.mipmap.km}\n" +
            "  ,{\"kn\":R.mipmap.kn}\n" +
            "  ,{\"kp\":R.mipmap.kp}\n" +
            "  ,{\"kr\":R.mipmap.kr}\n" +
            "  ,{\"kw\":R.mipmap.kw}\n" +
            "  ,{\"ky\":R.mipmap.ky}\n" +
            "  ,{\"kz\":R.mipmap.kz}\n" +
            "  ,{\"la\":R.mipmap.la}\n" +
            "  ,{\"lb\":R.mipmap.lb}\n" +
            "  ,{\"lc\":R.mipmap.lc}\n" +
            "  ,{\"li\":R.mipmap.li}\n" +
            "  ,{\"lk\":R.mipmap.lk}\n" +
            "  ,{\"lr\":R.mipmap.lr}\n" +
            "  ,{\"ls\":R.mipmap.ls}\n" +
            "  ,{\"lt\":R.mipmap.lt}\n" +
            "  ,{\"lu\":R.mipmap.lu}\n" +
            "  ,{\"lv\":R.mipmap.lv}\n" +
            "  ,{\"ly\":R.mipmap.ly}\n" +
            "  ,{\"ma\":R.mipmap.ma}\n" +
            "  ,{\"mc\":R.mipmap.mc}\n" +
            "  ,{\"md\":R.mipmap.md}\n" +
            "  ,{\"me\":R.mipmap.me}\n" +
            "  ,{\"mf\":R.mipmap.mf}\n" +
            "  ,{\"mg\":R.mipmap.mg}\n" +
            "  ,{\"mh\":R.mipmap.mh}\n" +
            "  ,{\"mk\":R.mipmap.mk}\n" +
            "  ,{\"ml\":R.mipmap.ml}\n" +
            "  ,{\"mm\":R.mipmap.mm}\n" +
            "  ,{\"mn\":R.mipmap.mn}\n" +
            "  ,{\"mo\":R.mipmap.mo}\n" +
            "  ,{\"mp\":R.mipmap.mp}\n" +
            "  ,{\"mq\":R.mipmap.mq}\n" +
            "  ,{\"mr\":R.mipmap.mr}\n" +
            "  ,{\"ms\":R.mipmap.ms}\n" +
            "  ,{\"mt\":R.mipmap.mt}\n" +
            "  ,{\"mu\":R.mipmap.mu}\n" +
            "  ,{\"mv\":R.mipmap.mv}\n" +
            "  ,{\"mw\":R.mipmap.mw}\n" +
            "  ,{\"mx\":R.mipmap.mx}\n" +
            "  ,{\"my\":R.mipmap.my}\n" +
            "  ,{\"mz\":R.mipmap.mz}\n" +
            "  ,{\"na\":R.mipmap.na}\n" +
            "  ,{\"nc\":R.mipmap.nc}\n" +
            "  ,{\"ne\":R.mipmap.ne}\n" +
            "  ,{\"nf\":R.mipmap.nf}\n" +
            "  ,{\"ng\":R.mipmap.ng}\n" +
            "  ,{\"ni\":R.mipmap.ni}\n" +
            "  ,{\"nl\":R.mipmap.nl}\n" +
            "  ,{\"no\":R.mipmap.no}\n" +
            "  ,{\"np\":R.mipmap.np}\n" +
            "  ,{\"nr\":R.mipmap.nr}\n" +
            "  ,{\"nu\":R.mipmap.nu}\n" +
            "  ,{\"nz\":R.mipmap.nz}\n" +
            "  ,{\"om\":R.mipmap.om}\n" +
            "  ,{\"pa\":R.mipmap.pa}\n" +
            "  ,{\"pe\":R.mipmap.pe}\n" +
            "  ,{\"pf\":R.mipmap.pf}\n" +
            "  ,{\"pg\":R.mipmap.pg}\n" +
            "  ,{\"ph\":R.mipmap.ph}\n" +
            "  ,{\"pk\":R.mipmap.pk}\n" +
            "  ,{\"pl\":R.mipmap.pl}\n" +
            "  ,{\"pm\":R.mipmap.pm}\n" +
            "  ,{\"pn\":R.mipmap.pn}\n" +
            "  ,{\"pr\":R.mipmap.pr}\n" +
            "  ,{\"ps\":R.mipmap.ps}\n" +
            "  ,{\"pt\":R.mipmap.pt}\n" +
            "  ,{\"pw\":R.mipmap.pw}\n" +
            "  ,{\"py\":R.mipmap.py}\n" +
            "  ,{\"qa\":R.mipmap.qa}\n" +
            "  ,{\"re\":R.mipmap.re}\n" +
            "  ,{\"ro\":R.mipmap.ro}\n" +
            "  ,{\"rs\":R.mipmap.rs}\n" +
            "  ,{\"ru\":R.mipmap.ru}\n" +
            "  ,{\"rw\":R.mipmap.rw}\n" +
            "  ,{\"sa\":R.mipmap.sa}\n" +
            "  ,{\"sb\":R.mipmap.sb}\n" +
            "  ,{\"sc\":R.mipmap.sc}\n" +
            "  ,{\"sd\":R.mipmap.sd}\n" +
            "  ,{\"se\":R.mipmap.se}\n" +
            "  ,{\"sg\":R.mipmap.sg}\n" +
            "  ,{\"sh\":R.mipmap.sh}\n" +
            "  ,{\"si\":R.mipmap.si}\n" +
            "  ,{\"sj\":R.mipmap.sj}\n" +
            "  ,{\"sk\":R.mipmap.sk}\n" +
            "  ,{\"sl\":R.mipmap.sl}\n" +
            "  ,{\"sm\":R.mipmap.sm}\n" +
            "  ,{\"sn\":R.mipmap.sn}\n" +
            "  ,{\"so\":R.mipmap.so}\n" +
            "  ,{\"sr\":R.mipmap.sr}\n" +
            "  ,{\"ss\":R.mipmap.ss}\n" +
            "  ,{\"st\":R.mipmap.st}\n" +
            "  ,{\"sv\":R.mipmap.sv}\n" +
            "  ,{\"sx\":R.mipmap.sx}\n" +
            "  ,{\"sy\":R.mipmap.sy}\n" +
            "  ,{\"sz\":R.mipmap.sz}\n" +
            "  ,{\"tc\":R.mipmap.tc}\n" +
            "  ,{\"td\":R.mipmap.td}\n" +
            "  ,{\"tf\":R.mipmap.tf}\n" +
            "  ,{\"tg\":R.mipmap.tg}\n" +
            "  ,{\"th\":R.mipmap.th}\n" +
            "  ,{\"tj\":R.mipmap.tj}\n" +
            "  ,{\"tk\":R.mipmap.tk}\n" +
            "  ,{\"tl\":R.mipmap.tl}\n" +
            "  ,{\"tm\":R.mipmap.tm}\n" +
            "  ,{\"tn\":R.mipmap.tn}\n" +
            "  ,{\"to\":R.mipmap.to}\n" +
            "  ,{\"tr\":R.mipmap.tr}\n" +
            "  ,{\"tt\":R.mipmap.tt}\n" +
            "  ,{\"tv\":R.mipmap.tv}\n" +
            "  ,{\"tw\":R.mipmap.tw}\n" +
            "  ,{\"tz\":R.mipmap.tz}\n" +
            "  ,{\"ua\":R.mipmap.ua}\n" +
            "  ,{\"ug\":R.mipmap.ug}\n" +
            "  ,{\"um\":R.mipmap.um}\n" +
            "  ,{\"us\":R.mipmap.us}\n" +
            "  ,{\"uy\":R.mipmap.uy}\n" +
            "  ,{\"uz\":R.mipmap.uz}\n" +
            "  ,{\"va\":R.mipmap.va}\n" +
            "  ,{\"vc\":R.mipmap.vc}\n" +
            "  ,{\"ve\":R.mipmap.ve}\n" +
            "  ,{\"vg\":R.mipmap.vg}\n" +
            "  ,{\"vi\":R.mipmap.vi}\n" +
            "  ,{\"vn\":R.mipmap.vn}\n" +
            "  ,{\"vu\":R.mipmap.vu}\n" +
            "  ,{\"wf\":R.mipmap.wf}\n" +
            "  ,{\"ws\":R.mipmap.ws}\n" +
            "  ,{\"xk\":R.mipmap.xk}\n" +
            "  ,{\"ye\":R.mipmap.ye}\n" +
            "  ,{\"yt\":R.mipmap.yt}\n" +
            "  ,{\"za\":R.mipmap.za}\n" +
            "  ,{\"zm\":R.mipmap.zm}\n" +
            "  ,{\"zw\":R.mipmap.zw},\n" +
            "]";
}
